name: jira-reporting-docker
services:
- name: web
  # Docker image deployment instead of source-based
  image:
    registry_type: DOCKER_HUB
    repository: jira-reporter  # Change this to your actual Docker Hub username/repo
    tag: digitalocean
  instance_count: 1
  instance_size_slug: basic-xxs  # Can upgrade to basic-xs or higher for production
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_KEY
    value: "base64:8+igkz4+EsNA+E7e3G+gCQdbePDCNmpvOdykoZggzdg="
  - key: APP_NAME
    value: "JIRA Time Reporter"
  - key: APP_URL
    value: "https://jira-reporting-docker-yourname.ondigitalocean.app"  # Update with your app URL
  
  # Database Configuration (Neon PostgreSQL)
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ep-green-river-a5ojrjkn-pooler.us-east-2.aws.neon.tech
  - key: DB_PORT
    value: "5432"
  - key: DB_DATABASE
    value: jira_reporter
  - key: DB_USERNAME
    value: neondb_owner
  - key: DB_PASSWORD
    value: npg_Sq8A4BWgsTPl
  - key: DB_SSLMODE
    value: require
  
  # Redis Configuration (Redis Cloud)
  - key: REDIS_CLIENT
    value: phpredis
  - key: REDIS_URL
    value: "redis://default:sHH1dlPnzp2WOGJsrgHdgsXh8XLZdznq@redis-17950.c309.us-east-2-1.ec2.redns.redis-cloud.com:17950"
  - key: REDIS_HOST
    value: redis-17950.c309.us-east-2-1.ec2.redns.redis-cloud.com
  - key: REDIS_PORT
    value: "17950"
  - key: REDIS_PASSWORD
    value: sHH1dlPnzp2WOGJsrgHdgsXh8XLZdznq
  - key: REDIS_USERNAME
    value: default
  - key: REDIS_DB
    value: "0"
  - key: REDIS_CACHE_DB
    value: "1"
  
  # Cache and Session Configuration
  - key: CACHE_STORE
    value: redis
  - key: SESSION_DRIVER
    value: redis
  - key: QUEUE_CONNECTION
    value: redis
  
  # Laravel Optimization
  - key: OPTIMIZE_AUTOLOADER
    value: "true"
  - key: CONFIG_CACHE
    value: "true"
  - key: ROUTE_CACHE
    value: "true"
  - key: VIEW_CACHE
    value: "true"
  
  # JIRA Application Specific
  - key: LOG_CHANNEL
    value: stack
  - key: LOG_LEVEL
    value: info

# Optional: Background job processing worker
# Uncomment the section below if you need dedicated queue workers
#
# - name: worker
#   image:
#     registry_type: DOCKER_HUB
#     repository: jira-reporter  # Same image as web service
#     tag: digitalocean
#   instance_count: 1
#   instance_size_slug: basic-xxs
#   # Override command to run queue worker instead of web server
#   run_command: php artisan queue:work --queue=jira-sync-high,jira-sync-daily,jira-worklog-sync,jira-background,default --tries=3 --timeout=14400
#   envs:
#   # Include same environment variables as web service
#   - key: APP_ENV
#     value: production
#   # ... (repeat all necessary env vars from web service)

# Note: Using external services (Neon PostgreSQL + Redis Cloud)
# No managed databases needed in DigitalOcean App Platform