# DigitalOcean App Platform Configuration for JIRA Reporter
# Alpine-based Docker configuration (optimized and tested)

name: jira-reporter
region: nyc1

# Services Configuration
services:
  # Main Laravel Application
  - name: web
    source_dir: /jira-reporter
    github:
      repo: KarolisTusk/jira-reporter
      branch: main
      deploy_on_push: true
    
    # Docker Configuration (Alpine-based, optimized)
    dockerfile_path: Dockerfile
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP Configuration
    http_port: 8080
    
    # Environment Variables
    envs:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:8+igkz4+EsNA+E7e3G+gCQdbePDCNmpvOdykoZggzdg="
      - key: APP_NAME
        value: "JIRA Time Reporter"
      
      # Database Connection (Neon PostgreSQL)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-green-river-a5ojrjkn-pooler.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: jira_reporter
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_Sq8A4BWgsTPl
      - key: DB_SSLMODE
        value: require
      
      # Cache and Queue Configuration (Database-based for simplicity)
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      
      # Security
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: LOG_LEVEL
        value: error
      
      # Sentry Error Tracking
      - key: SENTRY_LARAVEL_DSN
        value: "https://6201d48e2849126b0c9e1f5db42d4396@o4509526861676544.ingest.us.sentry.io/4509526863577088"
      - key: SENTRY_ENVIRONMENT
        value: production
      - key: SENTRY_TRACES_SAMPLE_RATE
        value: "0.1"
      
      # Frontend Environment Variables
      - key: VITE_APP_NAME
        value: "JIRA Time Reporter"
      - key: VITE_APP_ENV
        value: production
      - key: VITE_SENTRY_DSN
        value: "https://59d8da25303031f0ec664fe407c593e3@o4509526861676544.ingest.us.sentry.io/4509526931013632"
      
      # Enhanced Sentry Database Tracking
      - key: SENTRY_TRACE_SQL_QUERIES_ENABLED
        value: "true"
      - key: SENTRY_TRACE_SQL_BINDINGS_ENABLED
        value: "false"
      - key: SENTRY_TRACE_SQL_ORIGIN_ENABLED
        value: "true"
      - key: SENTRY_TRACE_SQL_ORIGIN_THRESHOLD_MS
        value: "100"
      - key: SENTRY_BREADCRUMBS_SQL_QUERIES_ENABLED
        value: "true"
      - key: SENTRY_BREADCRUMBS_SQL_BINDINGS_ENABLED
        value: "false"
      
      # Sentry Source Maps Configuration
      - key: SENTRY_ORG
        value: "your-sentry-org"
      - key: SENTRY_PROJECT
        value: "your-sentry-project"
      - key: SENTRY_AUTH_TOKEN
        value: "your-auth-token"

# Database configuration is external (Neon PostgreSQL)

